# Generated by Django 2.0 on 2018-11-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_chh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chh',
        ),
    ]
